server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
    gateway:
      routes:
        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat/**

  discovery:
    locator:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
