server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

