server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
